name: storedge
description: "Inventory Management System"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  animations: ^2.0.11
  dotted_border: ^2.1.0
  entry: ^1.0.0
  flutter:
    sdk: flutter
  group_button: ^5.3.4
  image_picker: ^1.1.2
  intl: ^0.20.0
  path: ^1.9.0
  provider: ^6.1.2
  sqflite: ^2.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  fonts:
    - family: Plus Jakarta Sans
      fonts:
        - asset: assets/fonts/plus_jakarta/PlusJakartaSans-Regular.ttf
        - asset: assets/fonts/plus_jakarta/PlusJakartaSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/plus_jakarta/PlusJakartaSans-Bold.ttf
          weight: 700
  uses-material-design: true